### ISSUE TITLE
module 'cv2.dnn' has no attribute 'DictValue'

### ISSUE THREAD

**Issue by Quietwo69** [Keaneo/Scrubtitles#2]
Hello, I'd love to use this but I'm facing an issue with the below. Can you help me?

```
(base) pohsean@Pohs-MacBook-Pro ~ % python /Users/pohsean/Downloads/yo/VideoTextRemover.py
Traceback (most recent call last):
  File "/Users/pohsean/Downloads/yo/VideoTextRemover.py", line 2, in <module>
    import cv2
  File "/Users/pohsean/opt/miniconda3/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/Users/pohsean/opt/miniconda3/lib/python3.8/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/Users/pohsean/opt/miniconda3/lib/python3.8/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/Users/pohsean/opt/miniconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/pohsean/opt/miniconda3/lib/python3.8/site-packages/cv2/typing/__init__.py", line 168, in <module>
    LayerId = cv2.dnn.DictValue
AttributeError: module 'cv2.dnn' has no attribute 'DictValue'
```

**Comment by addyuchiha** [comment]
Specify the error more, also checkout the new branch its a enhanced version and I converted it into a fucntion which makes it more easy to use aswell
